const sentences = [
  'Global warming is likely to reach 1.5°C between 2030 and 2052 if it continues to increase at the current rate.',
  'Human-induced warming reached approximately 1°C above pre-industrial levels in 2017, increasing at 0.2°C per decade.',
  'Warming from anthropogenic emissions from the pre-industrial period to the present will persist for centuries to millennia.',
  'Warming from anthropogenic emissions will continue to cause further long-term changes in the climate system.',
  'Impacts on natural and human systems from global warming have already been observed.',
  'Many land and ocean ecosystems and some of the services they provide have already changed due to global warming.',
  'Sea level rise will continue beyond 2100 even if global warming is limited to 1.5°C in the 21st century.',
  'Irreversible loss of the Greenland ice sheet could result in multi-metre rise in sea level over hundreds to thousands of years.',
  'Marine ice sheet instability in Antarctica could result in multi-metre rise in sea level over hundreds to thousands of years.',
  'Increasing warming amplifies the exposure of small islands, low-lying coastal areas and deltas to the risks associated with sea level rise.',
  'On land, impacts on biodiversity and ecosystems, including species loss and extinction, are projected to be lower at 1.5°C of global warming compared to 2°C.',
  'Lack of global cooperation is a key impediment to achieving 1.5°C pathways.',
  'Lack of governance of the required energy and land transformation is a key impediment to achieving 1.5°C pathways.',
  'Increases in resource-intensive consumption are key impediments to achieving 1.5°C pathways.',
  'Under emissions in line with current pledges under the Paris Agreement, global warming is expected to surpass 1.5°C above pre-industrial levels.',
  'Lower GHG emissions in 2030 lead to a higher chance of keeping peak warming to 1.5°C.',
  'Limiting warming to 1.5°C implies deep reductions in emissions of non-CO2 forcers, particularly methane.',
  '1.5°C mitigation pathways are characterized by energy-demand reductions, decarbonization of electricity and other fuels, and electrification of energy end use.',
  '1.5°C mitigation pathways are characterized by deep reductions in agricultural emissions.',
  '1.5°C implies very ambitious, internationally cooperative policy environments that transform both supply and demand.',
  'Policies reflecting a high price on emissions are necessary in models to achieve cost-effective 1.5°C pathways.',
  'Limiting warming to 1.5°C requires a marked shift in investment patterns.',
  'The evolution of methane and sulphur dioxide emissions strongly influences the chances of limiting warming to 1.5°C.',
  'Pathways limiting warming to 1.5°C with no or limited overshoot use carbon dioxide removal to some extent to neutralize emissions from sources for which no mitigation measures have been identified',
  'Pathways limiting warming to 1.5°C with no or limited overshoot use carbon dioxide removal to achieve net negative emissions to return global warming to 1.5°C following a peak.',
  'Limits to our understanding of how the carbon cycle responds to net negative emissions increase the uncertainty about the effectiveness of carbon dioxide removal to decline temperatures after a peak.',
  'Carbon dioxide removal deployed at scale is unproven, and reliance on such technology is a major risk in the ability to limit warming to 1.5°C.',
  'Lifestyle choices lowering energy demand and the land- and GHG-intensity of food consumption can further support achievement of 1.5°C pathways.',
  'Limiting warming to 1.5°C can be achieved synergistically with poverty alleviation and improved energy security.',
  'Limiting warming to 1.5°C can provide large public health benefits through improved air quality, preventing millions of premature deaths.',
  'Warming greater than the global average has already been experienced in many regions and seasons, with higher average warming over land than over the ocean.',
  'Many of the impacts of warming up to and beyond 1.5°C fall disproportionately on the poor and vulnerable.',
  'Some potential impacts of mitigation actions required to limit warming to 1.5°C fall disproportionately on the poor and vulnerable.',
  'The global transformation that would be needed to limit warming to 1.5°C requires geophysical, environmental-ecological, technological, economic, socio-cultural and institutional change.',
  'Some risks may be long-lasting and irreversible, such as the loss of some ecosystems.',
  'If overshoot is to be minimized, large, immediate and unprecedented global efforts to mitigate greenhouse gases are required.',
  'Limiting global warming to 1.5°C would limit risks of increases in heavy precipitation events on a global scale.',
  'Limiting global warming to 1.5°C is expected to substantially reduce the probability of extreme drought, precipitation deficits, and risks associated with water availability.',
  'The ocean has absorbed about 30% of the anthropogenic carbon dioxide, resulting in ocean acidification and changes to carbonate chemistry that are unprecedented for at least the last 65 million years.',
  'There are multiple lines of evidence that ocean warming and acidification corresponding to 1.5°C of global warming would impact sectors such as aquaculture and fisheries.',
  'There are multiple lines of evidence that ocean warming and acidification corresponding to 1.5°C of global warming would impact a wide range of marine organisms and ecosystems.',
  'Risks associated with factors, such as forest fires, extreme weather events, and the spread of invasive species, pests and diseases, would be lower at 1.5°C than at 2°C of warming.',
  'Constraining global warming to 1.5°C, rather than to 2°C and higher, is projected to have many benefits for terrestrial and wetland ecosystems and for the preservation of their services to humans.',
  'Multiple lines of evidence indicate that 70–90% of warm water coral reefs that exist today will disappear even if global warming is constrained to 1.5°C.',
  'Reductions in projected food availability are larger at 2°C than at 1.5°C of global warming in the Sahel, southern Africa, the Mediterranean, central Europe and the Amazon.',
  'Fisheries and aquaculture are important to global food security but are already facing increasing risks from ocean warming and acidification.',
  'Land use and land-use change emerge as critical features of virtually all mitigation pathways that seek to limit global warming to 1.5°C.',
  'Any increase in global temperature is projected to affect human health, with primarily negative consequences.',
  'Lower risks are projected at 1.5°C than at 2°C for heat-related morbidity and mortality.',
  'Global warming of 2°C is expected to pose greater risks to urban areas than global warming of 1.5°C.',
  'Poverty and disadvantage have increased with recent warming and are expected to increase for many populations as average global temperatures increase from 1°C to 1.5°C and higher.',
  'Existing and restored natural coastal ecosystems may be effective in reducing the adverse impacts of rising sea levels and intensifying storms by protecting coastal and deltaic regions.'
]
